server:
  port: 8080
  spring:
    application:
      name: authentication
      datasource:
        url: jdbc:postgresql://localhost:5432/authentication
        username: devteam
        password: soksan
        driver-class-name: org.postgresql.Driver
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            format_sql: true
